import pool from './db.js';
import bcrypt from 'bcryptjs';

const createTables = async () => {
    const tableQueries = `

    -- 1. Users Table (Handles dual login panels: simple user & administrator)

    CREATE TABLE IF NOT EXISTS users (
        id SERIAL PRIMARY KEY,
        first_name VARCHAR(100) NOT NULL,
        last_name VARCHAR(100) NOT NULL,
        email VARCHAR(100) UNIQUE NOT NULL,
        phone_number VARCHAR(15) UNIQUE NOT NULL,
        password_hash VARCHAR(255) NOT NULL,
        role VARCHAR(20) NOT NULL DEFAULT 'user' CHECK (role IN ('user', 'admin')),
        account_type VARCHAR(100) NOT NULL DEFAULT 'standard',
        credit_score INT DEFAULT 750,
        monthly_income DECIMAL(12, 2) DEFAULT 85000.00,
        employment_type VARCHAR(50) DEFAULT 'Salaried',
        pan_number VARCHAR(20) DEFAULT 'ABCDE1234F',
        is_verified BOOLEAN DEFAULT FALSE,
        kyc_status VARCHAR(30) DEFAULT 'pending' CHECK (kyc_status IN ('pending', 'verified', 'rejected')),
        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);


--2. Banking products table/ Rate Table(SBI,HDFC,BOI,PNB,CBI,ICICI,AXIS,etc)

    CREATE TABLE IF NOT EXISTS bank_products(
        id SERIAL PRIMARY KEY,
        bank_name VARCHAR(30) NOT NULL,
        bank_code VARCHAR(30) NOT NULL,
        loan_type VARCHAR(100) NOT NULL,
        interest_rate_min DECIMAL(5,2) NOT NULL,
        interest_rate_max DECIMAL(5,2) NOT NULL,
        min_amount DECIMAL(12,2) NOT NULL,
        max_amount DECIMAL(12,2) NOT NULL,
        min_tenure_months INT NOT NULL,
        max_tenure_months INT NOT NULL,
        processing_fee_pct DECIMAL(4,2) NOT NULL,
        approval_rate_pct INT DEFAULT 90,
        features TEXT [] DEFAULT '{}',
        is_featured BOOLEAN DEFAULT FALSE,
        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

    



--3. Financial Profiles / Loan Applications Table;

    CREATE TABLE IF NOT EXISTS financial_profiles (
        id SERIAL PRIMARY KEY,
        application_id VARCHAR(100) UNIQUE NOT NULL,
        user_id INT REFERENCES users(id) ON DELETE CASCADE,
        bank_id INT REFERENCES bank_products(id) ON DELETE SET NULL,
        bank_name VARCHAR(100) NOT NULL,
        loan_type VARCHAR(100) NOT NULL,
        loan_amount DECIMAL(12, 2) NOT NULL,
        tenure_months INT NOT NULL DEFAULT 36,
        interest_rate DECIMAL(5, 2) NOT NULL,
        emi_amount DECIMAL(12,2) NOT NULL  DEFAULT 0.00,
        purpose VARCHAR(255) DEFAULT 'Personal Expenditure',
        employment_status VARCHAR(50) NOT NULL DEFAULT 'Salaried',
        annual_income DECIMAL(12,2) NOT NULL DEFAULT 1000000.00,
        existing_emi DECIMAL(12,2) NOT NULL DEFAULT 0.00,
        status VARCHAR(30) NOT NULL DEFAULT 'pending' CHECK (status IN ('pending','under_review', 'approved','missing_info','rejected')),
        ongoing_stats JSONB DEFAULT '{}',
        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

    -- 4. Documents Table (Attached documents per loan application)

    CREATE TABLE IF NOT EXISTS documents (
        id SERIAL PRIMARY KEY,
        application_id VARCHAR(100) REFERENCES financial_profiles(application_id) ON DELETE CASCADE,
        document_type VARCHAR(100) NOT NULL,
        document_name VARCHAR(255) NOT NULL,
        file_url TEXT NOT NULL,
        file_size INT DEFAULT 0,
        mime_type VARCHAR(100) DEFAULT 'application/pdf',
        status VARCHAR(20) NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'verified', 'rejected')),
        uploaded_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    );

    --5. Admin Queries Table (Handles missing info queries generated by admin)

    CREATE TABLE IF NOT EXISTS admin_queries (
        id SERIAL PRIMARY KEY,
        application_id VARCHAR(100) REFERENCES financial_profiles(application_id) ON DELETE CASCADE,
        user_id INT REFERENCES users(id) ON DELETE CASCADE,
        admin_id INT REFERENCES users(id) ON DELETE SET NULL,
        query_title VARCHAR(255) NOT NULL,
        query_details TEXT NOT NULL,
        missing_items TEXT[] DEFAULT '{}',
        user_response TEXT,
        is_resolved BOOLEAN DEFAULT FALSE,
        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        resolved_at TIMESTAMP
);
    -- 6. Notification Table (Simulated SMS/Email & In-App alert logs)
     CREATE TABLE IF NOT EXISTS notifications (
        id SERIAL PRIMARY KEY,
        user_id INT REFERENCES users(id) ON DELETE CASCADE,
        application_id VARCHAR(100) REFERENCES financial_profiles(application_id) ON DELETE CASCADE,
        type VARCHAR(30) NOT NULL CHECK (type IN ('sms', 'email', 'in_app')),
        recipient VARCHAR(100) NOT NULL,
        title VARCHAR(255) NOT NULL,
        message TEXT NOT NULL,
        status VARCHAR(30) DEFAULT 'delivered',
        sent_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    );
    -- 7. Linked Bank Accounts Table (SBI, HDFC, etc.)
    CREATE TABLE IF NOT EXISTS linked_bank_accounts (
        id SERIAL PRIMARY KEY,
        user_id INT REFERENCES users(id) ON DELETE CASCADE,
        bank_name VARCHAR(100) NOT NULL,
        bank_code VARCHAR(30) NOT NULL,
        account_number VARCHAR(50) NOT NULL,
        ifsc VARCHAR(20) NOT NULL,
        account_type VARCHAR(50) DEFAULT 'Savings',
        balance DECIMAL(12, 2) NOT NULL DEFAULT 50000.00,
        is_primary BOOLEAN DEFAULT FALSE,
        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    );
`;

    try {
        await pool.query(tableQueries);
        console.log('✅All PostgreSQL tables verified successfully!');
        await seedDefaultData();
    } catch (error) {
        console.error('❌Error creating database tables:', error.message);
    }
};

const seedDefaultData = async () => {

    try {

        // Seed default Admin & Demo user
        const salt = await bcrypt.genSalt(10);
        const adminPass = await bcrypt.hash('admin123', salt);

        const userPass = await bcrypt.hash('user123', salt);

        const adminCheck = await pool.query(
            "SELECT * FROM users WHERE email =$1",
            ["admin@sphere.com"]
        );

        if (adminCheck.rows.length === 0) {
            await pool.query(`
                    INSERT INTO users (first_name,last_name,email,phone_number,password_hash,role,
                    account_type,credit_score, monthly_income,employment_type,pan_number,
                    kyc_status) VALUES
                    ('Aman','Rawat','admin@sphere.com','+918888888888', $1, 'admin', 'administrator', 820, 150000.00, 'Banking Administrator', 'ADM999999Z', 'verified')
            `, [adminPass]);
            console.log('🌱 Seed: Created Admin user (admin@sphere.com / admin123)');
        }

        // Seed demo user

        const userCheck = await pool.query("SELECT * FROM users WHERE email = 'user@sphere.com'");
        if (userCheck.rows.length === 0) {
            await pool.query(`
                INSERT INTO users (first_name, last_name, email, phone_number, password_hash, role, account_type, credit_score, monthly_income, employment_type, pan_number, kyc_status)
                VALUES ('Devangee', 'Jain', 'user@sphere.com', '+919999999999', $1, 'user', 'salary', 765, 85000.00, 'Senior Software Engineer', 'ABCDE1234F', 'verified')
            `, [userPass]);
            console.log('🌱 Seed: Created Demo user (user@sphere.com / user123)');
        }
        // Seed Indian Bank Loan Products (SBI,HDFC, BOI, PNB, CBI, ICICI, Axis)
        const productsCount = await pool.query(`SELECT COUNT(*) AS count FROM bank_products`);
        if (parseInt(productsCount.rows[0].count) === 0) {
            const bankOfferings = [
                {
                    //SBI
                    bank_name: 'State Bank of India ',
                    bank_code: 'SBI',
                    loan_type: 'Home Loan',
                    interest_rate_min: 8.40,
                    interest_rate_max: 9.15,
                    min_amount: 500000,
                    max_amount: 50000000,
                    min_tenure_months: 12,
                    max_tenure_months: 360,
                    processing_fee_pct: 0.35,
                    approval_rate_pct: 94,
                    features: ['Zero Prepayment Charges', 'Concession for Women Borrowers', 'Overdraft Facility Available'],
                    is_featured: true
                },
                {
                    //HDFC
                    bank_name: 'HDFC Bank',
                    bank_code: 'HDFC',
                    loan_type: 'Home Loan',
                    interest_rate_min: 8.50,
                    interest_rate_max: 9.25,
                    min_amount: 500000,
                    max_amount: 4000000,
                    min_tenure_months: 12,
                    max_tenure_months: 60,
                    processing_fee_pct: 0.99,
                    approval_rate_pct: 92,
                    features: ['Instant Disbursal in 10 Sec', 'Minimal Paperwork', 'Flexible EMI Options'],
                    is_featured: true

                },
                {
                    //BOI

                    bank_name: 'Bank of India',
                    bank_code: 'BOI',
                    loan_type: 'Personal Loan',
                    interest_rate_min: 9.75,
                    interest_rate_max: 12.25,
                    min_amount: 50000,
                    max_amount: 2000000,
                    min_tenure_months: 12,
                    max_tenure_months: 84,
                    processing_fee_pct: 0.50,
                    approval_rate_pct: 89,
                    features: ['Low Interest for PSU Staff', 'Longer Tenure', 'Zero Hidden Charges'],
                    is_featured: false

                },
                {
                    //PNB
                    bank_name: 'Punjab National Bank',
                    bank_code: 'PNB',
                    loan_type: 'Auto Loan',
                    interest_rate_min: 8.65,
                    interest_rate_max: 10.20,
                    min_amount: 100000,
                    max_amount: 10000000,
                    min_tenure_months: 12,
                    max_tenure_months: 84,
                    processing_fee_pct: 0.25,
                    approval_rate_pct: 91,
                    features: ['90% On-Road Financing', 'Special EV Discount', 'Quick Sanction'],
                    is_featured: true
                },
                {
                    //CBI
                    bank_name: 'Central Bank of India',
                    bank_code: 'CBI',
                    loan_type: 'Education Loan',
                    interest_rate_min: 8.15,
                    interest_rate_max: 9.95,
                    min_amount: 100000,
                    max_amount: 15000000,
                    min_tenure_months: 24,
                    max_tenure_months: 180,
                    processing_fee_pct: 0.00,
                    approval_rate_pct: 95,
                    features: ['100% Financing for Premier Institutes', 'Moratorium Period + 1 Year', 'Zero Processing Fee'],
                    is_featured: true
                },
                {
                    //ICICI
                    bank_name: 'ICICI Bank',
                    bank_code: 'ICICI',
                    loan_type: 'Business Loan',
                    interest_rate_min: 11.25,
                    interest_rate_max: 16.50,
                    min_amount: 100000,
                    max_amount: 7500000,
                    min_tenure_months: 12,
                    max_tenure_months: 60,
                    processing_fee_pct: 1.25,
                    approval_rate_pct: 88,
                    features: ['Collateral-Free up to ₹50 Lakhs', 'GST-Based Sanctioning', 'Disbursal within 48 Hours'],
                    is_featured: true
                },
                {
                    //AXIS BANK
                    bank_name: 'Axis Bank',
                    bank_code: 'AXIS',
                    loan_type: 'Gold Loan',
                    interest_rate_min: 8.75,
                    interest_rate_max: 11.00,
                    min_amount: 25000,
                    max_amount: 2500000,
                    min_tenure_months: 6,
                    max_tenure_months: 36,
                    processing_fee_pct: 0.50,
                    approval_rate_pct: 98,
                    features: ['Same-Day Disbursal', 'High Per Gram Valuation', 'Safe Custody in Vault'],
                    is_featured: false
                }
            ];

            for (const offer of bankOfferings) {
                await pool.query(`
                    INSERT INTO bank_products (bank_name, bank_code, loan_type, interest_rate_min, interest_rate_max, min_amount, max_amount, min_tenure_months, max_tenure_months, processing_fee_pct, approval_rate_pct, features, is_featured)
                    VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13)
                `, [
                    offer.bank_name,
                    offer.bank_code,
                    offer.loan_type,
                    offer.interest_rate_min,
                    offer.interest_rate_max,
                    offer.min_amount,
                    offer.max_amount,
                    offer.min_tenure_months,
                    offer.max_tenure_months,
                    offer.processing_fee_pct,
                    offer.approval_rate_pct,
                    offer.features,
                    offer.is_featured
                ]);
            }
            console.log('🌱 Seed: Inserted Bank Products for SBI, HDFC, BOI, PNB, CBI, ICICI, AXIS.');
        }

    } catch (error) {
        console.error('❌Error seeding default data:', error.message);
    }
};



export default createTables;