import pool from './db.js';

const createTables = async () => {
    const queryText = `

    -- 1. Users Table (Handles dual login panels: simple user & administrator)

    CREATE TABLE IF NOT EXISTS users (
        id SERIAL PRIMARY KEY,
        first_name VARCHAR(100) NOT NULL,
        last_name VARCHAR(100) NOT NULL,
        email VARCHAR(100) UNIQUE NOT NULL,
        phone_number VARCHAR(15) UNIQUE NOT NULL,
        password_hash VARCHAR(255) NOT NULL,
        role VARCHAR(20) NOT NULL DEFAULT 'user' CHECK (role IN ('user', 'admin')),
        account_type VARCHAR(100) NOT NULL DEFAULT 'standard',
        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

--2. Financial Profiles / Loan Applications Table;

    CREATE TABLE IF NOT EXISTS financial_profiles (
        id SERIAL PRIMARY KEY,
        application_id VARCHAR(100) UNIQUE NOT NULL,
        user_id INT REFERENCES users(id) ON DELETE CASCADE,
        loan_type VARCHAR(100) NOT NULL,
        loan_amount DECIMAL(12, 2) NOT NULL,
        interest_rate DECIMAL(5, 2) NOT NULL,
        status VARCHAR(30) NOT NULL DEFAULT 'pending' CHECK (status IN ('under_review', 'approved','missing_info','rejected')),
        ongoing_stats JSONB DEFAULT '{}',
        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

    -- 3. Documents Table (Tracks attached required documents for loans)

    CREATE TABLE IF NOT EXISTS documents (
        id SERIAL PRIMARY KEY,
        profile_id INT REFERENCES financial_profiles(id) ON DELETE CASCADE,
        document_name VARCHAR(255) NOT NULL,
        file_url TEXT NOT NULL,
        uploaded_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    );

    --4. Admin Queries Table (Handles missing info queries generated by admin)

    CREATE TABLE IF NOT EXISTS admin_queries (
        id SERIAL PRIMARY KEY,
        profile_id INT REFERENCES financial_profiles(id) ON DELETE CASCADE,
        admin_id INT REFERENCES users(id) ON DELETE CASCADE,
        query_details TEXT NOT NULL,
        is_resolved BOOLEAN DEFAULT FALSE

);


`;

    try {
        await pool.query(queryText);
        console.log('All PostgreSQL tables (users, profiles, documents, queries) verified successfully!');
    } catch (error) {
        console.error('Error creating database tables:', error.message);
    }
};

export default createTables;